name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RUBYOPT: "-W:deprecated" # show warnings, deprecations only
      FARADAY_VERSION: ${{ matrix.faraday }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]
        faraday: [ '~> 1.0', '~> 2.0' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: |
          cp .env.test .env
          bundle exec rspec spec/
